context:
  shouldLoadCMS: true
  ğŸ“ shouldLoadCMS: because, in CMS, `shouldSkipPattern` "false" would not find stylesheet assets from CMS; but `shouldLoadCMS` lets core-cms.css provide x-drop-cap via s-drop-cap import
